[package]
name = "example-esp32s3"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
esp-backtrace = { version = "0", features = ["esp32s3", "panic-handler", "println"]}
#esp-backtrace = { version = "0.14", default-features = false, features = ["esp32s3", "exception-handler", "panic-handler", "println"] }
esp-hal = { version = "1.1.1", features = ["esp32s3", "unstable"] }
esp-println = { version = "0.14", features = ["esp32s3", "log-04"] }
esp-bootloader-esp-idf = { version = "0.5", features = ["esp32s3"] }
esp-alloc = "0.10"
critical-section = "1.2"
libm = "0.2"

oggopus-embedded = { path = "../oggopus-embedded", features = ["decode", "encode"] }
opus-embedded = { path = "../opus-embedded", features = ["decode", "encode", "stereo", "optimize_libopus"] }

[package.metadata.docs.rs]
all-features = true
default-target = "xtensa-esp32s3-none-elf"
targets = ["xtensa-esp32s3-none-elf"]
