[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[env]
#ESP_HAL_CONFIG_PSRAM_MODE = "octal"

[unstable]
build-std = ["core", "alloc"]
